#!/usr/bin/env python3

import random
import string
import sys
import pyperclip

# all char can add in pass
lowercase_letter = string.ascii_lowercase
uppercase_letter = string.ascii_uppercase
digits = string.digits
ponctuations = string.punctuation

# args
args_prefix = "-"
help_args = args_prefix + args_prefix + "help"
digits_args = "d"
uppercase_args = "u"
special_characters_args = "s"

# default len of pass
default_len = 8

clipboard_function_enabled = True

# function which generate the random string with a length and an alphabet
def generate_random_string(length, alphabet): 
  
  random_string = ""

  for i in range(length): 
    random_char = random.choice(alphabet)
    random_string += random_char
  
  return random_string

# function used to diplay help guide
def display_help():
  print("HELP menu : ")
  print()
  print("password                      generate a 8 length password with only lowercase char (default)")
  print("password <length>             generate a password with the length gived by user")
  print("password <length> [options]   you can add some options with or without the digits")
  print()
  print("List options : ")
  print()
  print("-u                            add uppercase letter in the password generated")
  print("-d                            add digits in the password generated")
  print("-s                            add special character in the password generated")
  print()
  print("end help - developed by Axel")
  print()

# function used to copy the password to the user's clipboard
def copy_password_to_user_clipboard(password):
  if clipboard_function_enabled:
    # copy the password to the user's clipboard
    pyperclip.copy(password)
    print("Password copied to clipboard")

# main function
def main(argv): 
  
  alphabet = lowercase_letter
  pass_len = default_len
  
  # process the arguments
  for opt in argv:
  
    if opt == help_args:
      display_help()
      sys.exit()
    elif opt.startswith("-"):
      split_str = [x for x in opt][1:]
      
      for c in split_str:
        if c == uppercase_args:
          alphabet += uppercase_letter
        elif c == digits_args:
          alphabet += digits
        elif c == special_characters_args:
          alphabet += ponctuations
        else: 
          print("Unknown parameter ! try " + help_args)
          sys.exit()
    else:
      try:
        float(opt)
        pass_len = int(opt)
      except ValueError:
        print("Unknown parameter ! Try " + help_args)
        sys.exit()
  


  # generate password
  password = generate_random_string(pass_len, alphabet)

  print(f"Your generated password: {password}")
  copy_password_to_user_clipboard(password)
  print("Tip: use the " + help_args + " option to display more details about the password command.")



if __name__ == "__main__" : 
  main(sys.argv[1:])
