#!/usr/bin/env python3

import random
import string
import sys

# all char can add in pass
lowercase_letter = string.ascii_lowercase
uppercase_letter = string.ascii_uppercase
digits = string.digits
ponctuations = string.punctuation

# default len of pass
default_len = 8

# function which generate the random string with a length and an alphabet
def generate_random_string(length, alphabet): 
  
  random_string = ""

  for i in range(length): 
    random_char = random.choice(alphabet)
    random_string += random_char
  
  return random_string

# function used to diplay help guide
def display_help():
  print("HELP menu : ")
  print()
  print("password                      generate a 8 length password with only lowercase char (default)")
  print()
  print("password <length>             generate a password with the length gived by user")
  print()
  print("password <length> [options]   you can add some options with or without the digits")
  print()
  print("List options : ")
  print()
  print("-u                            add uppercase letter in the password generated")
  print()
  print("-d                            add digits in the password generated")
  print()
  print("-s                            add special character in the password generated")
  print()
  print("end help - developed by Axel")
  print()

# main function
def main(argv): 
  
  alphabet = lowercase_letter
  pass_len = default_len
  
  #print(argv)

  # traité les arguments 
  for opt in argv:
  
    if opt == "--help":
      display_help()
      sys.exit()
    elif opt.startswith("-"):
      split_str = [x for x in opt][1:]
      
      for c in split_str:
        if c == "u":
          alphabet += uppercase_letter
        elif c == "d":
          alphabet += digits
        elif c == "s":
          alphabet += ponctuations
        else: 
          print("Unknown parameter ! try --help")
          sys.exit()
    else:
      try:
        float(opt)
        pass_len = int(opt)
      except ValueError:
        print("Unknown parameter ! Try --help")
        sys.exit()
  


  # generate password
  password = generate_random_string(pass_len, alphabet)

  print(password)


if __name__ == "__main__" : 
  main(sys.argv[1:])
